'use strict';
console.log('hello, world');
const $heading = document.querySelector('h1');
console.log('$heading', $heading);
console.dir($heading);
const $explanation = document.querySelector('#explanation');
console.log('$explanation', $explanation);
console.dir($explanation);
const $hint = document.querySelector('.hint');
console.log('$hint', $hint);
console.dir($hint);
const $p = document.querySelectorAll('p');
console.log($p);
const $links = document.querySelectorAll('.example-link');
console.log($links);
